# Data Preprocessing

## Objective:
- Load raw dataset
- Explore data
- Handle missing values & duplicates
- Normalize numerical features
- Save cleaned dataset for further analysis

In [1]:
# Import required libraries
import sys
import pandas as pd

# Add src folder to path so we can import our modules
sys.path.append('../src')

# Import preprocessing functions
from preprocessing import load_data, explore_data, clean_data, normalize_data, save_data

In [2]:
# Define file path
data_path = '../data/raw/mall_customers.csv'

# Load dataset
df = load_data(data_path)

# Display first 5 rows
df.head()

   CustomerID Gender   Age  Annual Income (k$)  Spending Score (1-100)
0        1000      M  39.0                59.9                    58.0
1        1001      M  34.0                48.4                    37.0
2        1002      F  40.0                70.5                    26.0
3        1003      F  47.0                81.1                    30.0
4        1004      F  33.0                42.1                    58.0

In [3]:
# Understand dataset structure
explore_data(df)

First 5 rows:
    CustomerID Gender   Age  Annual Income (k$)  Spending Score (1-100)
0        1000      M  39.0                59.9                    58.0
1        1001      M  34.0                48.4                    37.0
2        1002      F  40.0                70.5                    26.0
3        1003      F  47.0                81.1                    30.0
4        1004      F  33.0                42.1                    58.0

Dataset Info:

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              1000 non-null   int64
 1   Gender                  997 non-null    str
 2   Age                     994 non-null    float64
 3   Annual Income (k$)      996 non-null    float64
 4   Spending Score (1-100)  994 non-null    float64
dtypes: float64(3), int64(1), str(1)
memory usage: 39.2 KB
None

Missing Values:
 CustomerID                0
Gender                    3
Age                       6
Annual Income (k$)        4
Spending Score (1-100)    6
dtype: int64

In [4]:
# Remove missing values and duplicates
df = clean_data(df)

# Check again after cleaning
print("After Cleaning:")
print(df.isnull().sum())

After Cleaning:
CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [5]:
# Normalize Income and Spending Score
df = normalize_data(df)

# View updated dataset
df.head()

   CustomerID Gender   Age  Annual Income (k$)  Spending Score (1-100)
0        1000      M  39.0            0.347792                0.626374
1        1001      M  34.0            0.258714                0.395604
2        1002      F  40.0            0.429899                0.274725
3        1003      F  47.0            0.512006                0.318681
4        1004      F  33.0            0.209915                0.626374

In [6]:
# Define output path
output_path = '../data/processed/clean_data.csv'

# Save cleaned dataset
save_data(df, output_path)

print("✅ Clean data saved successfully!")

✅ Clean data saved successfully!

## Conclusion

- Dataset successfully cleaned
- Missing values and duplicates handled
- Data normalized for modeling
- Clean dataset saved for next steps (EDA, Clustering, etc.)

This dataset will now be used in further analysis.